include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    invalid_annotation_target: ignore
    missing_required_param: error
    missing_return: error
    todo: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - "**/generated/**"
    - "**/build/**"

linter:
  rules:
    # Core rules
    always_use_package_imports: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    cancel_subscriptions: true
    close_sinks: true
    use_build_context_synchronously: true

    # Style rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_positional_boolean_parameters: true
    avoid_unnecessary_containers: true
    await_only_futures: true
    camel_case_types: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    use_key_in_widget_constructors: true
    use_super_parameters: true
