// File generated by FlutterFire CLI.
// Run `flutterfire configure` to generate this file with your Firebase configuration

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you must run `flutterfire configure` first.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-ZlJ8-a5djNjCjb2qZGd184f7EvuRgfY',
    appId: '1:962306804861:android:e427031c4aa448117fb514',
    messagingSenderId: '962306804861',
    projectId: 'mbaretoyou',
    storageBucket: 'mbaretoyou.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4_yNcJXXeSszVGpAQYtcZnKSv6G5S2aQ',
    appId: '1:962306804861:ios:4dafb934bbbb4e817fb514',
    messagingSenderId: '962306804861',
    projectId: 'mbaretoyou',
    storageBucket: 'mbaretoyou.firebasestorage.app',
    iosBundleId: 'com.mbaretoyou.driverApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA21yYPhNHZopzCHJnV_OXz-ZbqHp0d6Ac',
    appId: '1:962306804861:web:445538bbf5dfa6f17fb514',
    messagingSenderId: '962306804861',
    projectId: 'mbaretoyou',
    authDomain: 'mbaretoyou.firebaseapp.com',
    storageBucket: 'mbaretoyou.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4_yNcJXXeSszVGpAQYtcZnKSv6G5S2aQ',
    appId: '1:962306804861:ios:0253e7bdd5629e1e7fb514',
    messagingSenderId: '962306804861',
    projectId: 'mbaretoyou',
    storageBucket: 'mbaretoyou.firebasestorage.app',
    iosBundleId: 'com.example.mbareToYou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA21yYPhNHZopzCHJnV_OXz-ZbqHp0d6Ac',
    appId: '1:962306804861:web:f52372bebc685c997fb514',
    messagingSenderId: '962306804861',
    projectId: 'mbaretoyou',
    authDomain: 'mbaretoyou.firebaseapp.com',
    storageBucket: 'mbaretoyou.firebasestorage.app',
  );
}